

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: glms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TheStrong!Password123"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - glms-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "TheStrong!Password123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  glms-api:
    build:
      context: .
      dockerfile: TechMoveGLMS.API/Dockerfile
    container_name: glms-api
    depends_on:
      sqlserver:
        condition: service_healthy
    
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=glms-sqlserver;Database=TechMoveDB;User Id=sa;Password=TheStrong!Password123;TrustServerCertificate=True;"
      Jwt__Key: "TheSuperSecretKeyThatIsAtLeast32CharactersLong!"
      Jwt__Issuer: "TechMoveAPI"
      Jwt__Audience: "TechMoveMVC"
    ports:
      - "5000:80"
    networks:
      - glms-network

  glms-web:
    build:
      context: .
      dockerfile: TechMoveGLMS/Dockerfile
    container_name: glms-web
    depends_on:
      - glms-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ApiBaseUrl: "http://glms-api:8080"
    ports:
      - "8080:8080"
    networks:
      - glms-network

volumes:
  sql_data:

networks:
  glms-network:
    driver: bridge
